### PR TITLE
Implement index switch. Resolve #290

### LINKED ISSUE #290: [Feature request] Switching PyPI mirror during installation
### Description of problem
I work in China and I suffer from slow connection to the genuine PyPI mirror. As the speed of downloading is around 20KB/s, other mirrors are widely used by Chinese developers. For example, TUNA in Tsinghua University provides a fast alternate which could be found at https://mirrors.tuna.tsinghua.edu.cn/pypi/ .

Normally, I would use pip configuration to switch mirrors. However in PlatformIO IDE for VSCode, I fails to do so. It takes patience and speed to kill the get-platformio.py at the right time and switch to a new mirror. I would have to manually run installation scripts later, after changing the mirror. It really bothers me, especially I am organizing a IoT club at my school. I have to do this kind of job for dozens of time.

It will be appreciated if PIO for VSCode can add a feature to let users choose their own mirror.

### Additional information
Posts on PlatformIO Community can be found at https://community.platformio.org/t/how-to-choose-another-pypi-mirror-in-python-env-bundled-with-pio/16570 .

### PR DESCRIPTION
**Pull request by CSharperMantle**
Resolves #290

Changes are only made in `pioinstaller` folder with no version changes, that is, the proposed PR doesn't change the `VERSION` const. Other actions may be required to correctly update the zipped content in `get-platformio.py` and bump the version.

### CODE REVIEW

**Comment by CSharperMantle** [comment]
Is this PR stale?

**Comment by ivankravets** [comment]
Thanks for the PR. We will review it soon!

**Comment by ivankravets** [comment]
It looks that `pip` has built-in support for `PIP_INDEX_URL` environment variable. Could you try to set it? 
```
PIP_INDEX_URL=https://mirrors.tuna.tsinghua.edu.cn/pypi/simple 
```

**Comment by CSharperMantle** [comment]
@ivankravets,
Thanks for the reply! `PIP_INDEX_URL` does work for me. But actually, my issue #290 is originally posted to solve the PlatformIO IDE for VSCode's issue, as it can be seen here:
> It will be appreciated if PIO for VSCode can add a feature to let users choose their own mirror.

As the issue is transferred to here, I came up with this PR. What I am actually seeking is a easy-to-use user interface on first-run installation process of PIO for VSCode, which can use code described in this PR as its backend.

**Comment by ivankravets** [comment]
Please re-test with https://raw.githubusercontent.com/platformio/platformio-core-installer/develop/get-platformio.py

We will provide a new setting in VSCode where you will be able to specify own PyPI Index URL.

I tested with
```
python get-platformio.py --pypi-index-url "https://mirrors.tuna.tsinghua.edu.cn/pypi/simple"
```

**Comment by CSharperMantle** [comment]
> Please re-test with https://raw.githubusercontent.com/platformio/platformio-core-installer/develop/get-platformio.py
> 
> We will provide a new setting in VSCode where you will be able to specify own PyPI Index URL.
> 
> I tested with
> 
> ```
> python get-platformio.py --pypi-index-url "https://mirrors.tuna.tsinghua.edu.cn/pypi/simple"
> ```

Thanks @ivankravets for shipping the functionality! I look forward to a future chance to contribute to PlatformIO.

**Comment by ivankravets** [comment]
Happy coding with PlatformIO!

**Pull request closed without merging**
